version: "3"
services:
  postgres:
    image: armhf/postgres:9.6-alpine
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  nginx:
    image: dlaion/raspberry-pi3-custon-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - logs:/var/log/nginx
      - codebase:/var/www/drupal
    depends_on:
      - php-fpm
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  php-fpm:
    image: dlaion/raspberry-pi3-custon-php
    depends_on:
      - postgres
    volumes:
      - logs:/var/log
      - codebase:/var/www/drupal
    ports:
      - "9000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  postgresql_data:
    driver: local
    driver_opts:
          type: nfs
          o: addr=10.88.0.1,rw
          device: ":/var/docker/lnpp/dbdata"
  codebase:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.88.0.1,rw
      device: ":/var/docker/lnpp/codebase"
  logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.88.0.1,rw
      device: ":/var/docker/lnpp/logs"
