version: "3"
services:
  postgres:
    image: armhf/postgres:9.6-alpine
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  nginx:
    image: dlaion/raspberry-pi3-custon-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/docker/lnpp/logs/nginx/:/var/log/nginx
      - /var/docker/lnpp/codebase:/var/www/drupal
    depends_on:
      - php-fpm
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  php-fpm:
    image: dlaion/raspberry-pi3-custon-php
    depends_on:
      - postgres
    volumes:
      - /var/docker/lnpp/logs/php/:/var/log
      - /var/docker/lnpp/codebase:/var/www/drupal
    ports:
      - "9000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  postgresql_data:
